AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CoachingOptimiserSageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"

  CoachingOptimiserModel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !GetAtt CoachingOptimiserSageMakerExecutionRole.Arn
      ModelName: !Sub "${AWS::StackName}-model"
      PrimaryContainer:
        Image: 763104351884.dkr.ecr.eu-west-2.amazonaws.com/tensorflow-inference:2.4-cpu
        ModelDataUrl: !Sub "s3://${S3Bucket}/optimiser/latest/optimiser"
        Environment:
          SAGEMAKER_PROGRAM: inference.py
          SAGEMAKER_SUBMIT_DIRECTORY: !Sub "s3://${S3Bucket}/optimiser/latest"
  
  CoachingOptimiserEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub "${AWS::StackName}-endpoint-config"
      ProductionVariants:
        - InitialInstanceCount: 1
          InstanceType: ml.t2.small
          ModelName: !Ref CoachingOptimiserModel
          VariantName: AllTraffic

  CoachingOptimiserEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub "${AWS::StackName}-endpoint"
      EndpointConfigName: !Ref CoachingOptimiserEndpointConfig
