AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3Bucket:
    Description: "The name of the S3 bucket that contains the model artifacts and inference script"
    Type: String
  S3ModelDataKey:
    Description: "The path to the model artifacts and inference script in the S3 bucket"
    Type: String

Resources:
  CoachingOptimiserSageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: 
                  - "arn:aws:s3:::blazemodelsregistry"
                  - "arn:aws:s3:::blazemodelsregistry/*"
        - PolicyName: SageMakerECRPublicAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr-public:GetDownloadUrlForLayer
                  - ecr-public:BatchGetImage
                  - ecr-public:BatchCheckLayerAvailability
                Resource: "*"


  CoachingOptimiserModel:
    Type: AWS::SageMaker::Model
    DependsOn: CoachingOptimiserSageMakerExecutionRole
    Properties:
      ExecutionRoleArn: !GetAtt CoachingOptimiserSageMakerExecutionRole.Arn
      ModelName: "CoachingOptimiser"
      PrimaryContainer:
        Image: 763104351884.dkr.ecr.eu-west-2.amazonaws.com/tensorflow-inference:2.4-cpu
        ModelDataUrl: !Sub "s3://${S3Bucket}/${S3ModelDataKey}/model/model.tar.gz"
        Environment:
          SAGEMAKER_PROGRAM: inference.py
          SAGEMAKER_SUBMIT_DIRECTORY: !Sub "s3://${S3Bucket}/${S3ModelDataKey}"
  
  CoachingOptimiserEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    DependsOn: CoachingOptimiserModel
    Properties:
      EndpointConfigName: "coaching-optimiser-endpoint-config"
      ProductionVariants:
        - ModelName: "CoachingOptimiser"
          VariantName: AllTraffic
          ServerlessConfig:
            MemorySizeInMB: 1024
            MaxConcurrency: 10

  CoachingOptimiserEndpoint:
    Type: AWS::SageMaker::Endpoint
    DependsOn: CoachingOptimiserEndpointConfig
    Properties:
      EndpointName: "coaching-optimiser-endpoint"
      EndpointConfigName: "coaching-optimiser-endpoint-config"
