name: Upload Model to S3

on:
  push:
    branches:
      - main

jobs:
  upload_model_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: List files for debugging
        run: |
          ls -R

      - name: Upload model to S3
        run: |
          aws s3 cp --recursive $GITHUB_WORKSPACE/model s3://blazemodelregistry/optimiser/latest/
