name: Upload Model to S3 and Deploy to SageMaker

on:
  push:
    branches:
      - main

jobs:
  upload_model_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload model to S3
        run: |
          aws s3 cp --recursive ./model s3://blazemodelsregistry/optimiser/latest/optimizer/

      - name: Upload inference script to S3
        run: |
          aws s3 cp ./src/inference_pipeline/inference.py s3://blazemodelsregistry/optimiser/latest/

  deploy_sagemaker:
    needs: upload_model_to_s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/template.yaml \
            --stack-name CoachingOptimiserDeploymentStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides S3Bucket=blazemodelsregistry S3ModelDataKey=optimiser/latest
