name: Upload Model to S3 and Deploy to SageMaker

on:
  push:
    branches:
      - main

jobs:
  upload_model_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Ensure assets directory exists and create placeholder if empty
        run: |
          mkdir -p ./model/optimiser/assets
          [ -z "$(ls -A ./model/optimiser/assets)" ] && touch ./model/optimiser/assets/.keep

      - name: Package model artifacts
        run: |
          tar -czvf model.tar.gz -C ./model/optimiser .

      - name: Upload model tarball to S3
        run: |
          aws s3 cp model.tar.gz s3://blazemodelsregistry/optimiser/latest/model/model.tar.gz

      - name: Upload inference script to S3
        run: |
          aws s3 cp ./src/inference_pipeline/inference.py s3://blazemodelsregistry/optimiser/latest/

      - name: Create ECR Policy JSON
        run: |
          echo '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AllowSageMakerPull",
                "Effect": "Allow",
                "Principal": {
                  "Service": "sagemaker.amazonaws.com"
                },
                "Action": [
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:BatchGetImage",
                  "ecr:BatchCheckLayerAvailability"
                ],
                "Resource": "arn:aws:ecr:eu-west-2:763104351884:repository/tensorflow-inference"
              }
            ]
          }' > ecr-policy.json

      - name: Set ECR Repository Policy
        run: |
          aws ecr set-repository-policy \
            --repository-name tensorflow-inference \
            --policy-text file://ecr-policy.json
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  

  
  deploy_sagemaker:
    needs: upload_model_to_s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/template.yaml \
            --stack-name CoachingOptimiserDeploymentStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides S3Bucket=blazemodelsregistry S3ModelDataKey=optimiser/latest
